stages:
  - build
  - test
  - publish


.image: &image
  image: quay.io/pypa/manylinux2014_x86_64


.build:
  <<: *image
  stage: build
  script:
  - ./build_wheels.sh
  artifacts:
    paths:
    - dist/*.whl


devel:
  extends: .build
  artifacts:
    expire_in: 8 hours
  except:
  - tags


release:
  extends: .build
  artifacts:
    expire_in: 1000 years
  only:
  - tags


test:
  <<: *image
  stage: test
  script:
    - ./test.sh


publish:
  stage: publish
  script:
  - ./publish-wheels.sh
  only:
  - tags
