devel:
  image: quay.io/pypa/manylinux1_x86_64
  stage: build
  script:
  - ./build_wheels.sh
  artifacts:
    paths:
    - ./*.whl
    expire_in: 8 hours
  except:
  - tags

release:
  image: quay.io/pypa/manylinux1_x86_64
  stage: build
  script:
  - ./build_wheels.sh
  artifacts:
    paths:
    - ./*.whl
  only:
  - tags
