#!python
"""Cat msgpack files.
"""
import os.path as pt
import reprlib

from datadings.reader import MsgpackReader


def cat(infile, maxstring):
    r = reprlib.Repr()
    r.maxstring = maxstring
    reader = MsgpackReader(infile)
    for sample in reader:
        print(r.repr(sample))


def main():
    from datadings.argparse import make_parser
    from datadings.argparse import argument_infile

    parser = make_parser(__doc__)
    argument_infile(parser, help='File to cat.')
    parser.add_argument(
        '-s', '--maxstring',
        default=40,
        type=int,
        help='max length of strings',
    )
    args, unknown = parser.parse_known_args()
    infile = pt.abspath(args.infile)
    cat(infile, args.maxstring)


def entry():
    try:
        main()
    except KeyboardInterrupt:
        pass
    finally:
        print()


if __name__ == '__main__':
    entry()
